// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDanDGvatxKD1V15TSZGTVlnpYkejqO6og',
    appId: '1:908474994105:web:3f7398c1feed1666b73a68',
    messagingSenderId: '908474994105',
    projectId: 'attendprov1',
    authDomain: 'attendprov1.firebaseapp.com',
    storageBucket: 'attendprov1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFx7wX2N2SNnAf_ErLVX8_Fqqd8aqf49c',
    appId: '1:908474994105:android:6c1e29daf6837d66b73a68',
    messagingSenderId: '908474994105',
    projectId: 'attendprov1',
    storageBucket: 'attendprov1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0SzxmpHhm8FnFmCauHG0ENhS9YYXikhY',
    appId: '1:908474994105:ios:549c7c33d49f2c05b73a68',
    messagingSenderId: '908474994105',
    projectId: 'attendprov1',
    storageBucket: 'attendprov1.firebasestorage.app',
    iosBundleId: 'com.example.qrAttend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0SzxmpHhm8FnFmCauHG0ENhS9YYXikhY',
    appId: '1:908474994105:ios:549c7c33d49f2c05b73a68',
    messagingSenderId: '908474994105',
    projectId: 'attendprov1',
    storageBucket: 'attendprov1.firebasestorage.app',
    iosBundleId: 'com.example.qrAttend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDanDGvatxKD1V15TSZGTVlnpYkejqO6og',
    appId: '1:908474994105:web:6d7d1d78630f9665b73a68',
    messagingSenderId: '908474994105',
    projectId: 'attendprov1',
    authDomain: 'attendprov1.firebaseapp.com',
    storageBucket: 'attendprov1.firebasestorage.app',
  );
}
